# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: homecage.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


class RecordingMode(betterproto.Enum):
    MODE_CONTINOUS = 0
    MODE_INTERVAL = 1


class RecordingState(betterproto.Enum):
    STATE_EMPTY = 0
    STATE_IDLE = 1
    STATE_RECORDING = 2
    STATE_WAITING = 3
    STATE_ERROR = 4


class RecordingStatus(betterproto.Enum):
    STATUS_RECORDING = 0
    STATUS_WAITING = 1
    STATUS_READY = 2
    STATUS_ERROR = 3


class DeviceType(betterproto.Enum):
    TYPE_RPI = 0
    TYPE_SERVER = 1
    TYPE_WEBAPP = 2


class Commands(betterproto.Enum):
    CMD_EMPTY = 0
    CMD_REQ_DEVICE_INFO = 1
    CMD_RES_DEVICE_INFO = 2
    CMD_REQ_SET_RECORDING_STATE = 3
    CMD_REQ_GET_RECORDING_STATE = 4
    CMD_RES_GET_RECORDING_STATE = 5


@dataclass(eq=False, repr=False)
class HomecageCommand(betterproto.Message):
    client_name: str = betterproto.string_field(1)
    command: "Commands" = betterproto.enum_field(2)
    res_device_info: "ResDeviceInfo" = betterproto.message_field(3, group="msg")
    res_get_recording_state: "ResGetRecordingState" = betterproto.message_field(
        4, group="msg"
    )
    req_set_recording_state: "ReqSetRecordingState" = betterproto.message_field(
        5, group="msg"
    )


@dataclass(eq=False, repr=False)
class ReqSetRecordingState(betterproto.Message):
    state: "RecordingState" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class ResGetRecordingState(betterproto.Message):
    state: "RecordingState" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class ResDeviceInfo(betterproto.Message):
    device_infos: List["DeviceInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CameraDevice(betterproto.Message):
    id: int = betterproto.int32_field(1)
    width: int = betterproto.int32_field(2)
    height: int = betterproto.int32_field(3)
    channels: int = betterproto.int32_field(4)
    fps: int = betterproto.int32_field(5)
    enconding: str = betterproto.string_field(6)
    type: str = betterproto.string_field(7)
    state: "RecordingState" = betterproto.enum_field(8)
    mode: "RecordingMode" = betterproto.enum_field(9)
    status: "RecordingStatus" = betterproto.enum_field(10)
    shedule: int = betterproto.int32_field(11)


@dataclass(eq=False, repr=False)
class Storage(betterproto.Message):
    total: int = betterproto.int64_field(1)
    free: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class DeviceInfo(betterproto.Message):
    device_name: str = betterproto.string_field(1)
    device_type: "DeviceType" = betterproto.enum_field(2)
    cameras: List["CameraDevice"] = betterproto.message_field(3)
    storage: "Storage" = betterproto.message_field(4)
